### PR TITLE
V1.1.0 - Major Update

### PR DESCRIPTION
**Pull request by akzhy**
This update includes:

 - Image loading library which optimizes image loading time by placing a small blurred image while the actual image loads. (Couldn't fully test this on local machine as images load fast)
 - Changed the structure of data files such that each markdown files are placed inside a directory with it's name being the URL
 - Due to the above change ^, images and other files can now be placed inside the directory, which makes editing and creating new items more easier.
- Some minor changes.

**Please don't merge this without testing, there may be bugs.**

### CODE REVIEW

**Comment by Athul-CA** [comment]
Really loved what you did on the department images

**Comment by akzhy** [comment]
Made it a standard way so that changing images and adding new departments will be much easier

**Comment by Athul-CA** [comment]
Let's wait for @samanyuneelson 's feedback too before merging

**Comment by akzhy** [comment]
Should we merge it now ? I've got some new updates. And I haven't found any bugs till now.

**Comment by Athul-CA** [comment]
Okay..  Merging it

**Pull request merged**
