### PR TITLE
V1.0.0

### PR DESCRIPTION
**Pull request by akzhy**
Major stable version

Fixed:

 - Announcements and News
 - Address on navbar and contact
 - Navbar top overlapping sidenav
 - Both logos on mobile
 - Some general broken stylings

### CODE REVIEW

**Comment by Athul-CA** [comment]
Did it work?

**Comment by Athul-CA** [comment]
:heart_eyes:

**Comment by akzhy** [comment]
Works on my machine 😁

**Comment by Athul-CA** [comment]
Build is fine as with the deploy preview

**Pull request merged**
