### PR TITLE
v2.0.0.0

### PR DESCRIPTION
**Pull request by akzhy**
# Version 2

Changes:

* Removed JQuery and materialize as dependencies
* Data folder moved outside `src`
* `anchors` changed to Gatsby `Link`, switching pages will now be 2x faster.
* Changed layout of Home page
* Minor design changes
* CSS file now split into different less modules/files
* Improved SEO

## Data Adding

**Do not** use `git push` to add data. The folder structure has been changed. So to add data, choose the upload option and upload only the data folder.

### May have bugs 😀.

### CODE REVIEW

**Comment by athul** [comment]
Good redesign 🤑🤑

**Comment by akzhy** [comment]
😍

**Comment by akzhy** [comment]
We may need to create a bot that checks if each image groups are of same aspect ratio. Layout may break if they have different aspect ratios.

**Comment by akzhy** [comment]
Merge cheyyatte @Akhil017  @athul @GokulDas027 @samanyuneelson

**Comment by athul** [comment]
Cheyyunnathin enik virodham illa but @samanyuneelson okke onn nokkiyitt
approve cheyyatte.... Alteast he is the project lead
Kind Regards,
Athul Cyriac Ajay,
GitHub Campus Expert,
Organizing Committee,
Meenachil Hacks,
College of Engineering Kidangoor

**Comment by akzhy** [comment]
```
Kind Regards,
Athul Cyriac Ajay,
GitHub Campus Expert,
Organizing Committee,
Meenachil Hacks,
College of Engineering Kidangoor
```

😳

**Comment by athul** [comment]
> ```
> Kind Regards,
> Athul Cyriac Ajay,
> GitHub Campus Expert,
> Organizing Committee,
> Meenachil Hacks,
> College of Engineering Kidangoor
> ```

Email Signature for sponsorship for Hackathon😅😅😅

**Comment by akzhy** [comment]
Samanyu has approved the merge. Merging now.

**Pull request merged**
