### PR TITLE
10th

### PR DESCRIPTION
**Pull request by samanyuneelson**

### CODE REVIEW

**Comment by athul** [comment]
Hey @samanyuneelson try pulling these and building it

**Comment by athul** [comment]
Hey @akzhy these are the logs
```bash
error #95313 TypeError: Cannot read property 'publicURL' of null
10:15:06 PM: Building static HTML failed for path "/faculty/shihabudeen-h/"
10:15:06 PM: See our docs page for more info on this error: https://gatsby.dev/debug-html
10:15:07 PM: 
10:15:07 PM:   TypeError: Cannot read property 'publicURL' of null
10:15:07 PM:   
10:15:07 PM:   - render-page.js:16876 ./src/templates/faculties.js.__webpack_exports__.defaul    t
10:15:07 PM:     /opt/build/repo/public/render-page.js:16876:176
10:15:07 PM:   
10:15:07 PM:   - react-dom-server.node.production.min.js:36 c
10:15:07 PM:     [repo]/[react-dom]/cjs/react-dom-server.node.production.min.js:36:500
10:15:07 PM:   
10:15:07 PM:   - react-dom-server.node.production.min.js:39 Ua
10:15:07 PM:     [repo]/[react-dom]/cjs/react-dom-server.node.production.min.js:39:16
10:15:07 PM:   
10:15:07 PM:   - react-dom-server.node.production.min.js:45 a.render
10:15:07 PM:     [repo]/[react-dom]/cjs/react-dom-server.node.production.min.js:45:48
10:15:07 PM:   
10:15:07 PM:   - react-dom-server.node.production.min.js:44 a.read
10:15:07 PM:     [repo]/[react-dom]/cjs/react-dom-server.node.production.min.js:44:161
10:15:07 PM:   
10:15:07 PM:   - react-dom-server.node.production.min.js:55 renderToString
10:15:07 PM:     [repo]/[react-dom]/cjs/react-dom-server.node.production.min.js:55:83
10:15:07 PM:   
10:15:07 PM:   - render-page.js:552 Module../.cache/static-entry.js.__webpack_exports__.defau    lt
10:15:07 PM:     /opt/build/repo/public/render-page.js:552:28
10:15:07 PM:   
10:15:07 PM:   - render-html.js:35 Promise
10:15:07 PM:     [repo]/[gatsby]/dist/utils/worker/render-html.js:35:36
10:15:07 PM:   
10:15:07 PM:   - debuggability.js:313 Promise._execute
10:15:07 PM:     [repo]/[bluebird]/js/release/debuggability.js:313:9
10:15:07 PM:   
10:15:07 PM:   - promise.js:488 Promise._resolveFromExecutor
10:15:07 PM:     [repo]/[bluebird]/js/release/promise.js:488:18
10:15:07 PM:   
10:15:07 PM:   - promise.js:79 new Promise
10:15:07 PM:     [repo]/[bluebird]/js/release/promise.js:79:10
10:15:07 PM:   
10:15:07 PM:   - render-html.js:31 Promise.map.path
10:15:07 PM:     [repo]/[gatsby]/dist/utils/worker/render-html.js:31:37
10:15:07 PM:   
10:15:07 PM:   - util.js:16 tryCatcher
10:15:07 PM:     [repo]/[bluebird]/js/release/util.js:16:23
10:15:07 PM:   
10:15:07 PM:   - map.js:61 MappingPromiseArray._promiseFulfilled
10:15:07 PM:     [repo]/[bluebird]/js/release/map.js:61:38
10:15:07 PM:   
10:15:07 PM:   - promise_array.js:114 MappingPromiseArray.PromiseArray._iterate
10:15:07 PM:     [repo]/[bluebird]/js/release/promise_array.js:114:31
10:15:07 PM:   
10:15:07 PM:   - promise_array.js:78 MappingPromiseArray.init
10:15:07 PM:     [repo]/[bluebird]/js/release/promise_array.js:78:10
10:15:07 PM:   
10:15:07 PM: 
```

**Comment by samanyuneelson** [comment]
Ok

**Comment by samanyuneelson** [comment]
image

**Comment by samanyuneelson** [comment]
childsharp error on CS dept page

**Pull request merged**
