### PR TITLE
V2.1.2.1

### PR DESCRIPTION
**Pull request by akzhy**
* (Hopefully) fixed issues with images

### The issues were due to missing images. If there are no images in the directory, remove the image property, do not leave it empty or place dummy text.

### CODE REVIEW

**Comment by akzhy** [comment]
Pheww.... 😃✨

**Comment by athul** [comment]
Yay. What abt the other one #36

**Comment by akzhy** [comment]
@athul  Delete.

**Comment by athul** [comment]
Okay

**Comment by samanyuneelson** [comment]
every thing solved? @akzhy

**Comment by akzhy** [comment]
Solved @samanyu

**Pull request merged**
