### PR TITLE
picture size changes ..done

### PR DESCRIPTION
**Pull request by samanyuneelson**
navbar rearrangement ..done
make cerd page ..done
create other pages .. 13/13 done
 page 2(publications) no data.
 page 4(post graduate)no data.
 page 5(undergraduate) no data.
 page 6(Syllabus) not working.
 page 7(Tequip) no data.
 page 8(Central Computer facility) no data.
 page 9(Library) no data.
 page 10(Office) no data.
 page 11(Transport) no data.
 page 12(Hostel) no data.
 page 13(Other) no data.
quicklinks data added ..done

### CODE REVIEW

**Comment by akzhy** [comment]
Does this run locally ?

**Comment by samanyuneelson** [comment]
> Does this run locally ?

yes

**Comment by akzhy** [comment]
@athul Can you clear cache from netlify ?

**Comment by athul** [comment]
Cache Problem

**Comment by athul** [comment]
🎉🎉🎉

**Pull request merged**
