### PR TITLE
V2.1.3.3

### PR DESCRIPTION
**Pull request by samanyuneelson**

### CODE REVIEW

**Comment by samanyuneelson** [comment]
@akzhy  and @athul  deployment failure again, how can i access the details of the failed deployment. I think the problem is with my last commit where i tried adding photos to page.

**Comment by samanyuneelson** [comment]
image

**Comment by athul** [comment]
Netlify works... If either of this is passing its totally fine

**Comment by samanyuneelson** [comment]
ok

**Pull request merged**
